# Generated by Django 3.1.3 on 2020-11-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201127_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='avatar',
        ),
    ]
